### ISSUE TITLE
Enchantment Checking Missing

### ISSUE THREAD

**Issue by xDazlD** [Geeveloper/MaxRepairCost#1]
**Server Version**
Spigot 1.13.2

**Plugin Version**
B.1.03 - BETA

**Describe the bug**
Players can add any enchantment to any item

**To Reproduce**
Put an item and book with incompatible enchantments into an anvil.

**Media**
![Screenshot from 2019-04-02 19-58-44](https://user-images.githubusercontent.com/32212089/55445857-e8b81b80-5582-11e9-8eb7-1ab98c3cef75.png)

**Comment by Geeveloper** [comment]
I will look into resolving this issue as soon as I can. Thank you for the report.

**Comment by Geeveloper** [comment]
Issue has now been resolved. Please check the spigot page later for a major update that includes a fix for this bug. Thank you for your patience and reporting it. Be sure to report any further bugs you encounter with the future updates.
